"""specs/m2-segmentation.md Done-when: 're-run with 5% noise on potential
changes tier for < 10% of HCPs.' Uses the real 2,000-row fixture generated by
scripts/generate_hcp_fixture.py.
"""

from datetime import date
from pathlib import Path

import numpy as np
import pytest

from agents.m2.hcp_mode import run_hcp_mode
from ingest.hcp_csv import load_hcp_csv
from packs.loader import load_pack
from tests.factories import make_brand

FIXTURE_CSV = Path(__file__).parent.parent / "fixtures" / "hcp_sample_india.csv"


def _tier_by_hcp_id(brand, pack, hcps, as_of):
    _, segments, target_lists = run_hcp_mode(
        brand, pack, hcps, target_share=0.05, personas_by_id={}, as_of=as_of
    )
    tier_by_segment_id = {s.id: s.tier for s in segments}
    return {
        entry.hcp_id: tier_by_segment_id[tl.segment_id]
        for tl in target_lists
        for entry in tl.entries
    }


@pytest.mark.skipif(not FIXTURE_CSV.exists(), reason="run scripts.generate_hcp_fixture first")
def test_tier_stability_under_five_percent_noise():
    pack = load_pack("india")
    brand = make_brand()
    as_of = date.today()
    hcps = load_hcp_csv(FIXTURE_CSV, pack, as_of=as_of)

    baseline = _tier_by_hcp_id(brand, pack, hcps, as_of)

    rng = np.random.default_rng(123)
    noisy_hcps = []
    for hcp in hcps:
        noisy = hcp.model_copy(deep=True)
        factor = 1 + rng.uniform(-0.05, 0.05)
        noisy.potential = hcp.potential.model_copy(update={"value": hcp.potential.value * factor})
        noisy_hcps.append(noisy)

    noisy_tiers = _tier_by_hcp_id(brand, pack, noisy_hcps, as_of)

    changed = sum(1 for hcp in hcps if baseline[hcp.id] != noisy_tiers[hcp.id])
    fraction_changed = changed / len(hcps)

    assert fraction_changed < 0.10, f"{fraction_changed:.1%} of {len(hcps)} HCPs changed tier under 5% noise"
