"""One-off, seeded generator for fixtures/call_notes_india.csv.

    uv run python -m scripts.generate_call_notes_fixture

Not part of the runtime package — a dev utility. Templated, not LLM-generated
(so building this fixture never needs a live API key). Templates are written
to plausibly cluster into something resembling
fixtures/brand_s_semaglutide_india.yaml's expected_personas (evidence purist /
pragmatic prescriber / cautious adopter / busy volume doctor) — the same
"plantable" approach that fixture's known_facts used for M1.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

N_NOTES = 200
N_UNIQUE_HCPS = 140  # some HCPs get more than one note
SEED = 7

OUT_PATH = Path(__file__).parent.parent / "fixtures" / "call_notes_india.csv"

# Each archetype maps loosely to one of the fixture's expected_personas.
# Multiple phrasings per archetype for lexical variety.
TEMPLATES = {
    "evidence_purist": [
        "Dr. spent most of the visit asking about the bioequivalence data for the generic "
        "competitors — worried the newer entrants haven't published real trial data.",
        "Raised concerns about quality consistency of generic semaglutide; wants to see peer-"
        "reviewed evidence before switching any stable patients.",
        "Asked for the latest guideline position on GLP-1 sequencing and whether our data holds "
        "up against the originator brand.",
        "Skeptical of manufacturer claims without published clinical trial backing; requested "
        "reprints of the pivotal studies.",
        "Said they only trust brands with strong regulatory and trial documentation given how "
        "crowded the generic market has become.",
    ],
    "pragmatic_prescriber": [
        "Main concern was patient affordability — most of their patients are price-sensitive and "
        "cost drives the prescribing decision more than anything else.",
        "Asked about patient assistance programs since many patients drop off therapy once they "
        "see the monthly cost.",
        "Prefers whichever option is cheapest for the patient, as long as it's not clearly "
        "inferior; cost is the deciding factor in this practice.",
        "Mentioned that out-of-pocket burden is the single biggest barrier to starting GLP-1 "
        "therapy for their patient population.",
        "Wants a lower price point or bundled patient support before considering a switch from "
        "the generic they currently prescribe.",
    ],
    "cautious_adopter": [
        "Hesitant about titration — had a bad experience with GI side effects in an early patient "
        "and now starts everyone on a very slow up-titration schedule.",
        "Asked detailed questions about nausea and tolerability management during the first "
        "few weeks of therapy.",
        "Wants a clear titration protocol and patient counseling materials before prescribing "
        "more broadly; tolerability is the top concern.",
        "Cited GI side effects as the reason two patients discontinued last quarter; wary of "
        "starting more patients without better support.",
        "Prefers to go slow with new patients on GLP-1s given how common tolerability issues have "
        "been in their practice.",
    ],
    "busy_volume_doctor": [
        "Very short visit — sees a high volume of patients daily and has little time to discuss "
        "new therapies in detail; wants a one-line takeaway.",
        "Said consult time is the constraint, not the science — needs something that doesn't add "
        "counseling burden to an already packed schedule.",
        "Asked for a quick-reference card rather than a full discussion; convenience for both "
        "doctor and patient is what matters most here.",
        "Prefers options that require minimal follow-up given patient volume; convenience of "
        "dosing was the main topic.",
        "Only had two minutes between patients; flagged that simplicity of the regimen matters "
        "more than marginal efficacy differences.",
    ],
}

HEADER_COMMENT = """\
# fixtures/call_notes_india.csv
# Synthetic rep call notes for Brand S (fixtures/brand_s_semaglutide_india.yaml).
# Generated by scripts/generate_call_notes_fixture.py, numpy seed={seed}, {n} rows.
# Templated, not LLM-generated — illustrative only, not real call notes.
# Written to plausibly cluster into ~4 personas resembling that fixture's
# expected_personas (evidence purist / pragmatic prescriber / cautious
# adopter / busy volume doctor); some HCPs (crm_id) have more than one note.
""".format(seed=SEED, n=N_NOTES)


def generate() -> pd.DataFrame:
    rng = np.random.default_rng(SEED)
    archetypes = list(TEMPLATES)

    hcp_ids = [f"HCP{i:04d}" for i in range(N_UNIQUE_HCPS)]
    # Each HCP leans toward one archetype across their notes (a realistic
    # doctor doesn't flip persona note to note), but not perfectly — a little
    # noise keeps clustering honest rather than trivial.
    hcp_archetype = {hcp: rng.choice(archetypes) for hcp in hcp_ids}

    notes = []
    for i in range(N_NOTES):
        hcp_id = hcp_ids[i % N_UNIQUE_HCPS] if i < N_UNIQUE_HCPS else rng.choice(hcp_ids)
        archetype = hcp_archetype[hcp_id] if rng.random() < 0.85 else rng.choice(archetypes)
        text = rng.choice(TEMPLATES[archetype])
        notes.append(
            {
                "note_id": f"NOTE{i:04d}",
                "crm_id": hcp_id,
                "date": f"2026-{rng.integers(1, 9):02d}-{rng.integers(1, 28):02d}",
                "text": text,
            }
        )

    rng.shuffle(notes)
    return pd.DataFrame(notes)


def main() -> None:
    df = generate()
    with open(OUT_PATH, "w") as f:
        f.write(HEADER_COMMENT)
        df.to_csv(f, index=False)
    print(f"wrote {len(df)} rows to {OUT_PATH}")


if __name__ == "__main__":
    main()
