"""One-off, seeded generator for fixtures/hcp_sample_india.csv.

    uv run python -m scripts.generate_hcp_fixture

Not part of the runtime package — a dev utility, run once to produce the
committed CSV (regenerate only if you deliberately want a new sample).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

N_ROWS = 2000
SEED = 42

OUT_PATH = Path(__file__).parent.parent / "fixtures" / "hcp_sample_india.csv"

# Matches packs/india/pack.yaml's potential_proxies.specialty_weight keys.
# Skewed toward diabetologist/endocrinologist/consulting_physician, since
# those are the specialties that actually prescribe a GLP-1 brand — a real
# HCP universe extract for this brand would look similar, not a uniform
# sample of all Indian physicians.
SPECIALTIES = ["diabetologist", "endocrinologist", "consulting_physician", "cardiologist", "gp"]
SPECIALTY_PROBS = [0.22, 0.18, 0.28, 0.10, 0.22]

# Matches pack's setting_weight keys.
SETTINGS = ["hospital", "clinic", "both"]
SETTING_PROBS = [0.35, 0.45, 0.20]

# Matches pack's city_tier_weight keys. Skewed tier2/tier3: most of India's
# prescriber volume for a mass-market category sits outside metros.
CITY_TIER_LOCATIONS = {
    "metro": [
        ("Maharashtra", "Mumbai"),
        ("Delhi", "New Delhi"),
        ("Karnataka", "Bengaluru"),
        ("Tamil Nadu", "Chennai"),
        ("West Bengal", "Kolkata"),
    ],
    "tier1": [
        ("Maharashtra", "Pune"),
        ("Gujarat", "Ahmedabad"),
        ("Telangana", "Hyderabad"),
        ("Rajasthan", "Jaipur"),
    ],
    "tier2": [
        ("Maharashtra", "Nagpur"),
        ("Madhya Pradesh", "Indore"),
        ("Gujarat", "Surat"),
        ("Uttar Pradesh", "Lucknow"),
    ],
    "tier3": [
        ("Uttar Pradesh", "Meerut"),
        ("Bihar", "Patna"),
        ("Odisha", "Cuttack"),
        ("Punjab", "Ludhiana"),
    ],
}
CITY_TIERS = list(CITY_TIER_LOCATIONS)
CITY_TIER_PROBS = [0.15, 0.20, 0.35, 0.30]

# No pack config maps rep_class to anything — kept as a plain descriptive
# label (common pharma field-force classification), not a scoring input.
REP_CLASSES = ["A", "B", "C", "D"]
REP_CLASS_PROBS = [0.15, 0.30, 0.35, 0.20]

# Skewed toward restricted/unknown: realistic field-access friction, not every
# HCP is freely visitable.
ACCESS_LEVELS = ["open", "restricted", "no_see", "unknown"]
ACCESS_PROBS = [0.25, 0.40, 0.10, 0.25]

HEADER_COMMENT = """\
# fixtures/hcp_sample_india.csv
# Synthetic HCP universe for Brand S (fixtures/brand_s_semaglutide_india.yaml).
# Generated by scripts/generate_hcp_fixture.py, numpy seed={seed}, {n} rows.
# Illustrative only — not real HCP data. Distributions are documented in that
# script's docstring/comments: specialty skewed toward diabetologist/
# endocrinologist/consulting_physician; city_tier skewed toward tier2/tier3;
# access skewed toward restricted/unknown; WhatsApp consent rate set higher
# than email (matches the India pack's channel mix); patient_volume_estimate
# is log-normal (most HCPs moderate volume, a long tail of high-volume ones).
""".format(seed=SEED, n=N_ROWS)


def generate() -> pd.DataFrame:
    rng = np.random.default_rng(SEED)

    specialty = rng.choice(SPECIALTIES, size=N_ROWS, p=SPECIALTY_PROBS)
    setting = rng.choice(SETTINGS, size=N_ROWS, p=SETTING_PROBS)
    city_tier = rng.choice(CITY_TIERS, size=N_ROWS, p=CITY_TIER_PROBS)
    rep_class = rng.choice(REP_CLASSES, size=N_ROWS, p=REP_CLASS_PROBS)
    access = rng.choice(ACCESS_LEVELS, size=N_ROWS, p=ACCESS_PROBS)
    consent_email = rng.random(N_ROWS) < 0.35
    consent_whatsapp = rng.random(N_ROWS) < 0.55
    patient_volume_estimate = rng.lognormal(mean=3.5, sigma=0.6, size=N_ROWS).round(1)

    states, cities, territories = [], [], []
    for tier in city_tier:
        state, city = CITY_TIER_LOCATIONS[tier][rng.integers(0, len(CITY_TIER_LOCATIONS[tier]))]
        states.append(state)
        cities.append(city)
        territories.append(f"{state[:2].upper()}-{rng.integers(1, 10)}")

    return pd.DataFrame(
        {
            "crm_id": [f"HCP{i:05d}" for i in range(N_ROWS)],
            "specialty": specialty,
            "setting": setting,
            "state": states,
            "city": cities,
            "city_tier": city_tier,
            "territory_id": territories,
            "rep_class": rep_class,
            "access": access,
            "consent_email": consent_email,
            "consent_whatsapp": consent_whatsapp,
            "patient_volume_estimate": patient_volume_estimate,
        }
    )


def main() -> None:
    df = generate()
    with open(OUT_PATH, "w") as f:
        f.write(HEADER_COMMENT)
        df.to_csv(f, index=False)
    print(f"wrote {len(df)} rows to {OUT_PATH}")


if __name__ == "__main__":
    main()
